/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      animation: {
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'pop': 'pop 0.3s ease-out',
        'blob': 'blob 7s infinite',
        'spin-slow': 'spin 3s linear infinite',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': {
            opacity: '0',
            transform: 'translateY(20px)'
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)'
          },
        },
        pop: {
          '0%': {
            transform: 'scale(0.95)',
            opacity: '0.5'
          },
          '100%': {
            transform: 'scale(1)',
            opacity: '1'
          },
        },
        blob: {
          '0%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
          '33%': {
            transform: 'translate(30px, -50px) scale(1.1)',
          },
          '66%': {
            transform: 'translate(-20px, 20px) scale(0.9)',
          },
          '100%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
  safelist: [
    'px-4',
    'py-2',
    'text-sm',
    'font-medium',
    'rounded-md',
    'bg-white',
    'text-gray-900',
    'shadow-sm',
    'ring-1',
    'ring-inset',
    'ring-gray-300',
    'hover:bg-gray-50',
    'bg-indigo-600',
    'text-white',
    'hover:bg-indigo-500',
    'focus-visible:outline',
    'focus-visible:outline-2',
    'focus-visible:outline-offset-2',
    'focus-visible:outline-indigo-600',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'h-4',
    'w-4',
    'h-5',
    'w-5',
    'h-6',
    'w-6',
    'h-7',
    'w-7',
    'h-8',
    'w-8',
    'text-indigo-600',
    'text-indigo-700',
    'text-gray-600',
    'text-gray-900',
    'text-white',
    'bg-indigo-100',
    'bg-indigo-200',
    'bg-indigo-500',
    'bg-purple-500',
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'rounded-full',
    'rounded-lg',
    'rounded-2xl',
    'rounded-3xl',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'hover:scale-105',
    'hover:shadow-xl',
    'hover:shadow-2xl',
    'hover:bg-indigo-50',
    'hover:text-indigo-600',
    'hover:text-indigo-700',
    'transition-all',
    'duration-200',
    'duration-300',
    'animate-fade-in-up',
    'animate-pop',
    'animate-bounce-slow',
    'animate-spin-slow',
    'animate-pulse',
    'animate-fade-in',
    'flex',
    'flex-col',
    'items-center',
    'items-start',
    'justify-center',
    'justify-between',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'gap-8',
    'gap-10',
    'p-3',
    'p-4',
    'p-10',
    'px-6',
    'px-8',
    'px-10',
    'px-12',
    'py-2',
    'py-4',
    'py-8',
    'py-16',
    'py-24',
    'pt-24',
    'pb-16',
    'pb-32',
    'mt-2',
    'mt-4',
    'mt-8',
    'mt-10',
    'mt-12',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-10',
    'mb-12',
    'mx-6',
    'mx-8',
    'mx-auto',
    'my-12',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-4xl',
    'text-6xl',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'tracking-tight',
    'leading-tight',
    'max-w-2xl',
    'max-w-4xl',
    'max-w-6xl',
    'max-w-7xl',
    'max-w-lg',
    'w-full',
    'min-h-screen',
    'relative',
    'sticky',
    'top-0',
    'z-10',
    'z-20',
    'overflow-x-hidden',
    'backdrop-blur-md',
    'border-b',
    'border-t',
    'border-2',
    'border-gray-100',
    'border-indigo-100',
    'border-indigo-500',
    'grid',
    'grid-cols-1',
    'md:grid-cols-3',
    'md:flex-row',
    'md:pb-32'
  ]
} 